### PR TITLE
zulip.py: Import zulip module

### PR DESCRIPTION
**Pull request by meetmangukiya**

### CODE REVIEW

**Comment by meetmangukiya** [comment]
Maybe we should consider renaming the backend module?

**Comment by derAnfaenger** [comment]
@meetmangukiya is there anything wrong with the current import a few lines below your change?

```python
 try:
     import zulip
 except ImportError:
     log.exception("Could not start the Zulip back-end")
     log.fatal(
         "You need to install the Zulip support in order "
         "to use the Zulip backend.\n"
         "You should be able to install this package using:\n"
         "pip install zulip"
     )
     sys.exit(1)
```

What name would you suggest for the backend module?

**Comment by meetmangukiya** [comment]
Interesting when I ran it, it didn't give me `ImportError` but an `AttributeError` Not sure why this didn't work 😕

**Comment by meetmangukiya** [comment]
This import works when the module is installed. So, I'd suggest we try to improve this such that it exits with an indication that the `zulip` module is not installed.

**Comment by meetmangukiya** [comment]
Closing since, it is fixed now

**Pull request closed without merging**
